### ISSUE TITLE
Clarity on Bluetooth Permission for Beacons & Eddystone Support

### ISSUE THREAD

**Issue by JoRoRadar** [radarlabs/documentation#189]
https://radar.com/documentation/beacons#how-it-works

We should clarify the distinction on beacon support: iOS **only** supports iBeacon and Android support both iBeacon and Eddystone. It is mentioned in the doc's but the current wording might lead to some misinterpretation.

We should also be super explicit about the need for Bluetooth permissions on Android. If we ever do get Eddystone support on iOS I think we need Bluetooth permissions for that as well. Given that permission prompting is a very sensitive topic this should almost have a dedicated section.

**Comment by jsani-radar** [comment]
Migrated to Linear: https://linear.app/radarlabs/issue/CORE-339/clarify-bluetooth-permissions-for-beacons-and-eddystone-support
