### ISSUE TITLE
Include SDK version requirements on important features and other changes

### ISSUE THREAD

**Issue by brettguenther** [radarlabs/documentation#218]
We should introduce an approach around comm'ing "introduced in vX.X" if we aren't going to be versioning docs any time soon.

This includes

- Remote tracking options
- Breaking SDK changes (i.e. foregroundServiceOptions change) 
- SDK requirements for new APIs (custom events, multi leg, etc)

**Comment by jsani-radar** [comment]
Migrated to Linear: https://linear.app/radarlabs/issue/CORE-345/include-sdk-version-requirements-on-important-features-and-other
