### ISSUE TITLE
Matrix far apart coordinates

### ISSUE THREAD

**Issue by preslyel** [radarlabs/documentation#68]
Hello, I've found an issue that when I tried to get distances matrix between Minnesota and NY I've got Bad request with a message - "Coordinates specified are too far apart". But request to the distance method with the same locations returns 200. I need to get hundreds of distances and making requests for each is not a good fit for me. Is it possible to get the right response with the matrix route? 
origins=43.877679,-95.134143
destinations=40.749667,-73.995909
&modes=car&units=imperial

**Comment by jsani-radar** [comment]
hey @preslyel, sorry for the late response

confirmed with one of our engineers that this is intended behavior - we're more lax on the limit for the distance calculation than we are for matrix distances given the parallel processing necessary to compute the latter
