### ISSUE TITLE
Add note about Android 11+ background location prompt changes

### ISSUE THREAD

**Issue by samfader** [radarlabs/documentation#77]
As of Android 11 and on, you need to deep link users into settings to allow for background location: https://developer.android.com/training/location/permissions#request-background-location

We should add a note to [this section](https://radar.io/documentation/sdk/android#request-permissions) of the Android SDK docs to reflect this. For example, there's an info box that says:

> Not seeing permissions prompts? First, make sure you've added permissions to your manifest. Second, check your device settings to make sure you haven't already granted location permissions.

We could potentially repurpose that, or add another one specific to Android 11+.

cc @nickpatrick @phil-brown @ahwreck

**Comment by phil-brown** [comment]
This is pretty interesting too https://developer.android.com/about/versions/11/privacy/location#request-background-location-separately

**Comment by jsani-radar** [comment]
migrated to Linear: https://linear.app/radarlabs/issue/CORE-335/add-a-note-about-android-11-bg-location-prompt-changes
